config/routes.rb
Rails.application.routes.draw do
  resources :news_histories
  resources :posts do 
    resources :comments
  end
   
  resources :categories
  resources :cates
  resources :kinds
  resources :cards

  get 'cates/:id/api', to: 'cates#api', as: 'api'

  
  resources :niifs do 
    member do
      get 'search', as: 'search'
      get 'detail/:detail_id', to: 'niifs#detail', as: 'niif_detail'
    end
  end
  resources :nics do
    # collection do
    #   get 'search_all', as: 'search_all'
    # end
    
    member do
      get 'search', as: 'search'
      get 'detail/:detail_id', to: 'nics#detail', as: 'nic_detail'
    end
  end
  
  devise_for :users, controllers: {
    session: 'users/sessions', registrations: 'users/registrations'
  }

  root to: "home#index"
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :card_cates
  has_many :cates, through: :card_cates

  has_many :card_kinds
  has_many :kinds, through: :card_kinds
end

app/models/card_cate.rb
class CardCate < ApplicationRecord
  belongs_to :card
  belongs_to :cate
end

app/models/card_kind.rb
class CardKind < ApplicationRecord
  belongs_to :card
  belongs_to :kind
end

app/models/cate.rb
class Cate < ApplicationRecord
  belongs_to :parent_cate, class_name: "Cate", optional: true, foreign_key: 'cate_id'
  has_many :children_cates, class_name: "Cate", foreign_key: 'cate_id'

  has_many :card_cates
  has_many :cards, through: :card_cates

  validates :name, presence: true

  def to_s
    name
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :nics
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :post
  belongs_to :user
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :textable, polymorphic: true

  enum label: %i[p h1 h2 h3 h4 h5 h6 footer]
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :users
end

app/models/kind.rb
class Kind < ApplicationRecord
  has_many :card_kinds
  has_many :cards, through: :card_kinds

  validates :name, uniqueness: true

  def to_s
    name
  end
end

app/models/news_history.rb
class NewsHistory < ApplicationRecord
  has_one_attached :document

  validates :title, presence: true
end

app/models/nic.rb
class Nic < ApplicationRecord
  belongs_to :category
  has_many :contents, as: :textable
end

app/models/niif.rb
class Niif < ApplicationRecord
  has_many :contents, as: :textable
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments
  validates :title, presence: true
    
end

app/models/profession.rb
class Profession < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :country
  belongs_to :profession

  has_many :posts
  has_many :comments


end

app/controllers/nics_controller.rb
class NicsController < ApplicationController
  before_action :set_nic, only: %i[ show edit update destroy search ]
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:detail]

  # GET /nics or /nics.json
  def index
    @nics = Nic.all.sort_by(&:number)
  end

  # GET /nics/1 or /nics/1.json
  def show
    @contents = @nic.contents.sort_by(&:order)
  end

  # GET /nics/new
  def new
    @nic = Nic.new
  end

  # GET /nics/1/edit
  def edit
  end

  # POST /nics or /nics.json
  def create
    @nic = Nic.new(nic_params)

    respond_to do |format|
      if @nic.save
        format.html { redirect_to @nic, notice: "Nic was successfully created." }
        format.json { render :show, status: :created, location: @nic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nics/1 or /nics/1.json
  def update
    respond_to do |format|
      if @nic.update(nic_params)
        format.html { redirect_to @nic, notice: "Nic was successfully updated." }
        format.json { render :show, status: :ok, location: @nic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nics/1 or /nics/1.json
  def destroy
    @nic.destroy
    respond_to do |format|
      format.html { redirect_to nics_url, notice: "Nic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @results = @nic.contents.where('text ilike ?', "%#{params[:s]}%").select(:text, :order, :number)

    respond_to do |format|
      format.js
    end
  end

  def detail
    @content_detail = @nic.contents.find_by(number: params[:detail_id])

    respond_to do |format|
      format.js { render partial: 'shared/detail' }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nic
      @nic = Nic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nic_params
      params.require(:nic).permit(:name, :number, :text, :category_id)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cates_helper.rb
module CatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/nics_helper.rb
module NicsHelper
end

app/helpers/niifs_helper.rb
module NiifsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/nics/_form.html.erb
<%= form_with(model: nic) do |form| %>
  <% if nic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nic.errors.count, "error") %> prohibited this nic from being saved:</h2>

      <ul>
        <% nic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nics/create.js.erb
$("form")[0].reset();
$("#cards").append("<%= escape_javascript(render partial: 'nic' locals: {nic: @nic}) %>");

app/views/nics/edit.html.erb
<h1>Editing Nic</h1>

<%= render 'form', nic: @nic %>

<%= link_to 'Show', @nic %> |
<%= link_to 'Back', nics_path %>

app/views/nics/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="container first">Nics</h1>

<table class="container text-center">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nics.each do |nic| %>
      <tr>
        <td><%= nic.number %>.- <%= nic.name %></td>
        <td><%= nic.category.name %></td>
        <td><%= link_to 'Mirar', nic, class: "btn btn-outline-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/nics/search.js.erb
console.log("<%= escape_javascript @results %>")
document.querySelector('#search-results .results').innerHTML = '<%= escape_javascript render 'shared/search/results', results: @results %>' 

app/views/nics/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container text-center">
<form class="form-inline-center search-form" action="<%= search_nic_path(@nic) %>" method="GET" data-remote="true">
  <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Search" name="s">
  <button class="btn btn-outline-danger my-2 my-ms-5 " type="submit">Buscar</button>
    <div id="search-results">
    
      <ul class="results"></ul>
    </div>
</form>
</div>

<div class="container text-center">
<p>
  <strong>Nic:</strong>
  <%= @nic.number %>.- <%= @nic.name %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @nic.category_id %>
</p>

<div id="content" class="container text-left">
<% @contents.map do |content| %>
<% if content.text.present? %>
  <%= render 'shared/tag_for', content: content, result_scope: 'nic' do %>    
  <% if content.number.present? %>
    <%= "#{content.number}.-" %>
    <% end %>

    <%= content.text.html_safe %>
  <% end %>
<% end %>
<% end %>
</div>
<div class="container text-center">
<%= link_to 'Atrás', nics_path, class: "btn btn-outline-danger" %>
</div>