config/routes.rb
Rails.application.routes.draw do
  resources :news_histories
  resources :posts do 
    resources :comments
  end
   
  resources :categories
  resources :cates
  resources :kinds
  resources :cards

  get 'cates/:id/api', to: 'cates#api', as: 'api'

  
  resources :niifs do 
    member do
      get 'search', as: 'search'
      get 'detail/:detail_id', to: 'niifs#detail', as: 'niif_detail'
    end
  end
  resources :nics do
    # collection do
    #   get 'search_all', as: 'search_all'
    # end
    
    member do
      get 'search', as: 'search'
      get 'detail/:detail_id', to: 'nics#detail', as: 'nic_detail'
    end
  end
  
  devise_for :users, controllers: {
    session: 'users/sessions', registrations: 'users/registrations'
  }

  root to: "home#index"
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :card_cates
  has_many :cates, through: :card_cates

  has_many :card_kinds
  has_many :kinds, through: :card_kinds
end

app/models/card_cate.rb
class CardCate < ApplicationRecord
  belongs_to :card
  belongs_to :cate
end

app/models/card_kind.rb
class CardKind < ApplicationRecord
  belongs_to :card
  belongs_to :kind
end

app/models/cate.rb
class Cate < ApplicationRecord
  belongs_to :parent_cate, class_name: "Cate", optional: true, foreign_key: 'cate_id'
  has_many :children_cates, class_name: "Cate", foreign_key: 'cate_id'

  has_many :card_cates
  has_many :cards, through: :card_cates

  validates :name, presence: true

  def to_s
    name
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :nics
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :post
  belongs_to :user
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :textable, polymorphic: true

  enum label: %i[p h1 h2 h3 h4 h5 h6 footer]
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :users
end

app/models/kind.rb
class Kind < ApplicationRecord
  has_many :card_kinds
  has_many :cards, through: :card_kinds

  validates :name, uniqueness: true

  def to_s
    name
  end
end

app/models/news_history.rb
class NewsHistory < ApplicationRecord
  has_one_attached :document

  validates :title, presence: true
end

app/models/nic.rb
class Nic < ApplicationRecord
  belongs_to :category
  has_many :contents, as: :textable
end

app/models/niif.rb
class Niif < ApplicationRecord
  has_many :contents, as: :textable
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments
  validates :title, presence: true
    
end

app/models/profession.rb
class Profession < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :country
  belongs_to :profession

  has_many :posts
  has_many :comments


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc)
    @comments = Comment.all
    @cards = Card.joins(:cates, :kinds).group("cates.id", "kinds.name").count
    @news_histories = NewsHistory.all.page(params[:page])
    @nics = Nic.group(:category_id).group("category_id").count
   # @nics = Nic.group("number", "category_id").count
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cates_helper.rb
module CatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/nics_helper.rb
module NicsHelper
end

app/helpers/niifs_helper.rb
module NiifsHelper
end

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<section id="info" class="row">
  <div class="col-sm-12 col-md-6 img-fluid card-deck">
    <hr>
      <%= image_tag 'img.jpg', width: 520, height: 330%>
  </div>
    <hr>
    
      <div id="inicio" class="Title container col-sm-12 col-md-6">
         <h1 class="text-center text-md-left my-5">NiifApp</h1>
         <% if current_user %>
         <h2 class="danger text-center">
         <%= flash[:alert] = "Welcome" %></h2>
         </button>
         <% end %>
        <hr>
       
   <div class="container">
    <div class="accordion" id="accordionExample">
      <div class="practice">
        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
          <div class="card-body">
          Bienvenido a NiifApp pensaba para y por usted, el profesional del Area Financiera que busca una manera fácil de acceder a las Normas Internacionales de Información Financiera y sus Normas Internacionales Contables. Le invito a darse una vuelta por nuestro NiifBlog donde compartiremos noticias sobre el mundo Financiero Contable adelante......
          </div>
        </div>
      </div>
  
    <div class="d-flex justify-content-center">
      <button type="button" class="btn btn-outline-secondary  text-nowrap" data-toggle="tooltip" data-placement="top" title="Presiona para enviar por correo">Consulta al correo </button>
      <button type="button" class="btn btn-outline-secondary seconde ml-3 text-nowrap" data-toggle="tooltip" data-placement="button" title="Presiona para suscribirte">Suscribete</button>          
    </div>  
  </div>
  <br>

</section>



<section id="comentario" class=" container">
  <hr class="hr-bottom d-none d-sm-block">
    <div class="row">
      <div class="col-sm-12 col-md-6 img fluid card-deck text-dark">
        <div class="card container text-left">
            <% @posts.each do |post| %>
              <img src="<%= post.image_url %>", width='150', height='250' class="card-img-top" alt="<%=post.title %>">
            <div class="card-body text-center">
              <h5 class="card-title"><%= post.title %></h5>
              <p class="card-text"><%= post.content %></p>
              <p class="card-text"><small class="text-muted"><%= post.created_at%></small></p>
              <%= render 'posts/post_comments', comments: post.comments.last(2) %>   
              <td><%= link_to 'Mirar', post, class:"btn btn-outline-danger" %></td>
            </div>
          <% end %>
          </div>   
        </div>
        <div class=" container text-center col-sm-12 col-md-6">
        <p class="grafic">Gráfico Distribución de Categorias de Nic</p>
        <%= bar_chart @nics %>
        <br>
        <p class="grafic">En el presente gráfico podemos ver la distribución de las Categorias en donde 11 de las mismas corresponden a la categoria 1, mientras que 4 unicamente corresponden a la categoria 2, 2 corresponden a la categoria de flujo de efectivo, 2 a la categoria 4 y 6 a la categoria 5.</p>
        <td><%= link_to 'Show', categories_path, class:"grafic" %></td>
      <hr>
    <br>
    
    
      <div class="content-header">
      <h3>Noticias</h3>
        <ul>
          <li>
            <%= link_to 'Lo que debes de saber sobre normas', asset_path('noticias-niif-marzo-2018.pdf'), class:"btn btn-outline-danger", target: '_blank'%>
            <span>March 30, 2018 at 8:00 PM EST</span>
          </li>
        <hr>
          <li>
            <%= link_to 'S&P Dow Jones Indices Anuncia Cambios en la Composición del S&P 500', asset_path('1358762_5var-6egov-202104-spanish.pdf'), class:"btn btn-outline-danger",  target: '_blank' %>
            <span>April 16, 2021 at 10:26 AM EDT</span>
          </li>
        <hr>
        <li>
          <%= link_to 'Análisis de la aplicación de las NIIF y NICSP aplicada a los pasivos corrientes (Resolución 414)', asset_path('2020_analisis_aplicacion_niif.pdf'), class:"btn btn-outline-danger", target: '_blank'%>
          <span>arch 30, 2018 at 8:00 PM EST</span>
        </li>
        <hr>
        
        <li>
          <%= link_to 'Analisis de Deloitte primer semestre del 2019', asset_path('Deloitte-ES-Audit-NewsletterContable-primer-semestre-2019.pdf'), class:"btn btn-outline-danger", target: '_blank'%>
          <span>March 19, 2021 at 4:20 PM EDT</span>
        </li>
        <hr>

        <li>
          <%= link_to 'S&P Dow Jones Indices Anuncia Actualizaciones a las directrices por Capitalización de Mercado del S&P Composite 1500', asset_path('20210504-spdji-digital-markets-launch-es.pdf'), class:"btn btn-outline-danger", target: '_blank' %>
          <span>March 19, 2021 at 4:20 PM EDT</span>
        </li>
        <hr>
           <%= link_to 'Más', news_histories_path, class: "btn btn-outline-danger" %>
      </ul>
    </div>
  <br>
</section>  

<hr>
 <div class="container text-center">
  <p class="grafic">Gráfico Categorias de Nics</p>
    <%= bar_chart @cards %>
    <br>
    <p class="grafic">El movimiento anual del mercado bursátil en Asia el último año. Como se representa en el gráfico los colores representan los Tipos diferentes de Nombres que representan la Banca y sus diferentes categorias de cuentas.</p>
    <td><%= link_to 'Show', cards_path, class:"grafic" %></td>
    </div>
    
<hr>
 <div class="carousel container">
    <div id="carouselExampleIndicators" class="carousel slide d-none d-sm-none d-md-block" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active indicator"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1" class="indicator"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="row">
                    <div class="col-3">
                    <%= image_tag 'descarga.jpg', width: 200, height: 200 %>
                    </div>
                    <div class="col-3">
                    <%= image_tag 'img.jpg', width: 200, height: 200 %>
                    </div>
                    <div class="col-3">
                    <%= image_tag 'index.jpg', width: 200, height: 200 %>
                    </div>
                    <div class="col-3">
                    <%= image_tag 'logo1.jpg', width: 200, height: 200 %>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="row">
                    <div class="col-3">
                    <%= image_tag 'descarga.jpg', width: 200, height: 200 %>
                    </div>
                    <div class="col-3">
                    <%= image_tag 'img.jpg', width: 200, height: 200 %>
                    </div>
                    <div class="col-3">
                    <%= image_tag 'logo1.jpg', width: 200, height: 200 %>
                    </div>
                    <div class="col-3">
                    <%= image_tag 'index.jpg', width: 200, height: 200 %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>