config/routes.rb
Rails.application.routes.draw do
  resources :news_histories
  resources :posts do 
    resources :comments
  end
   
  resources :categories
  resources :cates
  resources :kinds
  resources :cards

  get 'cates/:id/api', to: 'cates#api', as: 'api'

  
  resources :niifs do 
    member do
      get 'search', as: 'search'
      get 'detail/:detail_id', to: 'niifs#detail', as: 'niif_detail'
    end
  end
  resources :nics do
    # collection do
    #   get 'search_all', as: 'search_all'
    # end
    
    member do
      get 'search', as: 'search'
      get 'detail/:detail_id', to: 'nics#detail', as: 'nic_detail'
    end
  end
  
  devise_for :users, controllers: {
    session: 'users/sessions', registrations: 'users/registrations'
  }

  root to: "home#index"
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :card_cates
  has_many :cates, through: :card_cates

  has_many :card_kinds
  has_many :kinds, through: :card_kinds
end

app/models/card_cate.rb
class CardCate < ApplicationRecord
  belongs_to :card
  belongs_to :cate
end

app/models/card_kind.rb
class CardKind < ApplicationRecord
  belongs_to :card
  belongs_to :kind
end

app/models/cate.rb
class Cate < ApplicationRecord
  belongs_to :parent_cate, class_name: "Cate", optional: true, foreign_key: 'cate_id'
  has_many :children_cates, class_name: "Cate", foreign_key: 'cate_id'

  has_many :card_cates
  has_many :cards, through: :card_cates

  validates :name, presence: true

  def to_s
    name
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :nics
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :post
  belongs_to :user
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :textable, polymorphic: true

  enum label: %i[p h1 h2 h3 h4 h5 h6 footer]
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :users
end

app/models/kind.rb
class Kind < ApplicationRecord
  has_many :card_kinds
  has_many :cards, through: :card_kinds

  validates :name, uniqueness: true

  def to_s
    name
  end
end

app/models/news_history.rb
class NewsHistory < ApplicationRecord
  has_one_attached :document

  validates :title, presence: true
end

app/models/nic.rb
class Nic < ApplicationRecord
  belongs_to :category
  has_many :contents, as: :textable
end

app/models/niif.rb
class Niif < ApplicationRecord
  has_many :contents, as: :textable
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments
  validates :title, presence: true
    
end

app/models/profession.rb
class Profession < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :country
  belongs_to :profession

  has_many :posts
  has_many :comments


end

app/controllers/niifs_controller.rb
class NiifsController < ApplicationController
  before_action :set_niif, only: %i[ show edit update destroy search detail ]
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:detail]

  # GET /niifs or /niifs.json
  def index
    @niifs = Niif.all.sort_by(&:number)
  end

  # GET /niifs/1 or /niifs/1.json
  def show
    @contents = @niif.contents.sort_by(&:order)
  end

  # GET /niifs/new
  def new
    @niif = Niif.new
  end

  # GET /niifs/1/edit
  def edit
  end

  # POST /niifs or /niifs.json
  def create
    @niif = Niif.new(niif_params)

    respond_to do |format|
      if @niif.save
        format.html { redirect_to @niif, notice: "Niif was successfully created." }
        format.json { render :show, status: :created, location: @niif }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @niif.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /niifs/1 or /niifs/1.json
  def update
    respond_to do |format|
      if @niif.update(niif_params)
        format.html { redirect_to @niif, notice: "Niif was successfully updated." }
        format.json { render :show, status: :ok, location: @niif }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @niif.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /niifs/1 or /niifs/1.json
  def destroy
    @niif.destroy
    respond_to do |format|
      format.html { redirect_to niifs_url, notice: "Niif was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @results = @niif.contents.where('text ilike ?', "%#{params[:s]}%").select(:text, :order, :number)

    respond_to do |format|
      format.js
    end
  end

  def detail
    @content_detail = @niif.contents.find_by(number: params[:detail_id].downcase)

    respond_to do |format|
      format.js { render partial: 'shared/detail' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_niif
      @niif = Niif.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def niif_params
      params.require(:niif).permit(:name, :number, :text)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cates_helper.rb
module CatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/nics_helper.rb
module NicsHelper
end

app/helpers/niifs_helper.rb
module NiifsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/niifs/_form.html.erb
<%= form_with(model: niif) do |form| %>
  <% if niif.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(niif.errors.count, "error") %> prohibited this niif from being saved:</h2>

      <ul>
        <% niif.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/niifs/edit.html.erb
<h1>Editing Niif</h1>

<%= render 'form', niif: @niif %>

<%= link_to 'Show', @niif %> |
<%= link_to 'Back', niifs_path %>

app/views/niifs/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="container first">Niifs</h1>

<table class="container text-center">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Número</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="text-center">
    <% @niifs.each do |niif| %>
      <tr>
        <td><%= niif.name %></td>
        <td><%= niif.number %></td>
        <td><%= link_to 'Mirar', niif, class: "btn btn-outline-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/niifs/new.html.erb
<h1>New Niif</h1>

<%= render 'form', niif: @niif %>

<%= link_to 'Back', niifs_path %>

app/views/niifs/search.js.erb
console.log("<%= escape_javascript @results %>")
document.querySelector('#search-results .results').innerHTML = '<%= escape_javascript render 'shared/search/results', results: @results, result_scope: 'niif' %>' 

app/views/niifs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container text-center">
<form class="form-inline-center search-form" action="<%= search_niif_path(@niif) %>" method="GET" data-remote="true">
  <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Search" name="s">
  <button class="btn btn-outline-danger my-2 my-ms-5 " type="submit">Buscar</button>
    <div id="search-results">
      <ul class="results"></ul>
    </div>
</form>
</div>

<div class="container text-center">
<p>
  <strong>Nombre:</strong>
  <%= @niif.name %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @niif.number %>
</p>
</div>

<div id="content" class="container text-left">
<% @contents.map do |content| %>
<% if content.text.present? %>
  <%= render 'shared/tag_for', content: content, result_scope: 'niif' do %>
    <% if content.number.present? %>
    <%= "#{content.number}.-" %>
    <% end %>

    <%= content.text.html_safe %>
  <% end %>
<% end %>
<% end %>
</div>
<div class="container text-center">
<%=  link_to 'Atrás', niifs_path, class: "btn btn-outline-danger" %>
</div>