config/routes.rb
Rails.application.routes.draw do
  resources :news_histories
  resources :posts do 
    resources :comments
  end
   
  resources :categories
  resources :cates
  resources :kinds
  resources :cards

  get 'cates/:id/api', to: 'cates#api', as: 'api'

  
  resources :niifs do 
    member do
      get 'search', as: 'search'
      get 'detail/:detail_id', to: 'niifs#detail', as: 'niif_detail'
    end
  end
  resources :nics do
    # collection do
    #   get 'search_all', as: 'search_all'
    # end
    
    member do
      get 'search', as: 'search'
      get 'detail/:detail_id', to: 'nics#detail', as: 'nic_detail'
    end
  end
  
  devise_for :users, controllers: {
    session: 'users/sessions', registrations: 'users/registrations'
  }

  root to: "home#index"
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :card_cates
  has_many :cates, through: :card_cates

  has_many :card_kinds
  has_many :kinds, through: :card_kinds
end

app/models/card_cate.rb
class CardCate < ApplicationRecord
  belongs_to :card
  belongs_to :cate
end

app/models/card_kind.rb
class CardKind < ApplicationRecord
  belongs_to :card
  belongs_to :kind
end

app/models/cate.rb
class Cate < ApplicationRecord
  belongs_to :parent_cate, class_name: "Cate", optional: true, foreign_key: 'cate_id'
  has_many :children_cates, class_name: "Cate", foreign_key: 'cate_id'

  has_many :card_cates
  has_many :cards, through: :card_cates

  validates :name, presence: true

  def to_s
    name
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :nics
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :post
  belongs_to :user
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :textable, polymorphic: true

  enum label: %i[p h1 h2 h3 h4 h5 h6 footer]
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :users
end

app/models/kind.rb
class Kind < ApplicationRecord
  has_many :card_kinds
  has_many :cards, through: :card_kinds

  validates :name, uniqueness: true

  def to_s
    name
  end
end

app/models/news_history.rb
class NewsHistory < ApplicationRecord
  has_one_attached :document

  validates :title, presence: true
end

app/models/nic.rb
class Nic < ApplicationRecord
  belongs_to :category
  has_many :contents, as: :textable
end

app/models/niif.rb
class Niif < ApplicationRecord
  has_many :contents, as: :textable
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments
  validates :title, presence: true
    
end

app/models/profession.rb
class Profession < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :country
  belongs_to :profession

  has_many :posts
  has_many :comments


end

app/controllers/news_histories_controller.rb
class NewsHistoriesController < ApplicationController
  before_action :set_news_history, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /news_histories or /news_histories.json
  def index
    if params[:content].present?
      @news_histories = NewsHistory.where("title ilike ?", "%#{ params[:content] }%").page(params[:page]).per(5)
    else
      @news_histories = NewsHistory.all
    end
  end

  # GET /news_histories/1 or /news_histories/1.json
  def show
  end

  # GET /news_histories/new
  def new
    @news_history = NewsHistory.new
  end

  # GET /news_histories/1/edit
  def edit
  end

  # POST /news_histories or /news_histories.json
  def create
    @news_history = NewsHistory.new(news_history_params)

    respond_to do |format|
      if @news_history.save
        format.html { redirect_to @news_history, notice: "News history was successfully created." }
        format.json { render :show, status: :created, location: @news_history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_histories/1 or /news_histories/1.json
  def update
    respond_to do |format|
      if @news_history.update(news_history_params)
        format.html { redirect_to @news_history, notice: "News history was successfully updated." }
        format.json { render :show, status: :ok, location: @news_history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @news_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_histories/1 or /news_histories/1.json
  def destroy
    @news_history.destroy
    respond_to do |format|
      format.html { redirect_to news_histories_url, notice: "News history was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_history
      @news_history = NewsHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def news_history_params
      params.require(:news_history).permit(:title, :content)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cates_helper.rb
module CatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/news_histories_helper.rb
module NewsHistoriesHelper
end

app/helpers/nics_helper.rb
module NicsHelper
end

app/helpers/niifs_helper.rb
module NiifsHelper
end

app/views/news_histories/_form.html.erb
<%= form_with(model: news_history) do |form| %>
  <% if news_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news_history.errors.count, "error") %> prohibited this news_history from being saved:</h2>

      <ul>
        <% news_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="container text-center">
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  
  <br>
  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>
</div>

app/views/news_histories/edit.html.erb
<h1>Editing News History</h1>

<%= render 'form', news_history: @news_history %>

<%= link_to 'Show', @news_history %> |
<%= link_to 'Back', news_histories_path %>

app/views/news_histories/files.html.erb
<div class=" home-widget">
    <div class="content-header">
    

    <ul>
       <li>
      <%= link_to 'Lo que debes de saber sobre normas', asset_path('noticias-niif-marzo-2018.pdf'), class:"btn btn-outline-danger", target: '_blank'%>
       <span>March 30, 2018 at 8:00 PM EST</span>
      </li>

      <li>
      <%= link_to 'Noticias de Normas de Información Financiera', asset_path('noticias-niif-2020.pdf'), class:"btn btn-outline-danger",  target: '_blank'%>
       <span>October 01, 2020 at 11:00 PM EST</span>
      </li>
      <hr>

      
      <li>
        <%= link_to 'Análisis de la aplicación de las NIIF y NICSP aplicada a los pasivos corrientes (Resolución 414)', asset_path('2020_análisis_aplicación_niif.pdf'), target: '_blank' %>
        <span>Jun 22, 2020 at 11:15 AM EDT</span>
      </li>
      <hr>
      
      <li>
       <%= link_to 'Emision del decreto anual de la actualización normaativa en Colombia', asset_path('2021-0009-Emision-decreto-anual-de-actualizacion-normativa-en-Colombia.pdf'), target: '_blank' %>
       <span>March 16, 2021 at 3:42 PM EDT</span>
      </li>
      <hr>

       <li>
      <%= link_to 'Un afondo de las implicaciones de los efectos del coronavirus', asset_path('A-fondo-implicaciones-contables-de-los-efectos-del-coronavirus.pdf'), target: '_blank' %>
       <span>March 19, 2020 at 1:12 AM EDT</span>
      </li>
      <hr>
     
       <li>
      <%= link_to 'Boletín Mensual de Marzo Niif 2021', asset_path('Boletín_Marzo_2021.pdf'), target: '_blank'%>
       <span>March 12, 2021 at 9:20 PM EST</span>
      </li>
      <hr>

       <li>
      <%= link_to 'Analisis de Deloitte primer semestre del 2019', asset_path('Deloitte-ES-Audit-NewsletterContable-primer-semestre-2019.pdf'), target: '_blank' %>
       <span>March 19, 2021 at 4:20 PM EDT</span>
      </li>
      <hr>
    </ul>
  </div>
  </div>
  <br>

   

app/views/news_histories/index.html.erb
<p id="notice"><%= notice %></p>


<form class="form-inline-center container">
      <input class="form-control mr-sm-2" type="search1" placeholder="Search"
      aria-label="Search" name="content">
      <div class="text-center">
      <button class="btn btn-outline-danger my-2 my-ms-5"
      type="submit">Search</button>
      </div>
  </form>    


<h1 class="container">More News</h1>
<table >  
  <tbody>
    <% @news_histories.each do |news_history| %>
    <tr>
        <td class="container text-center"><%= news_history.title %>  
        <%= link_to news_history.document.filename, rails_blob_path(news_history.document, disposition: 'attachment'), class:"btn btn-outline-danger text-center", target: '_blank' %>
        <p class="card-text"><small class="text-muted"><%= news_history.created_at%></small></p><hr></td>
        <td><%= link_to 'Destroy', news_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    
<br>    
<div class="text-center">
<%= link_to 'New News History', new_news_history_path, class: "btn btn-outline-danger" %>
</div>

app/views/news_histories/new.html.erb
<h1 class="container">New News History</h1>

<%= render 'form', news_history: @news_history %>
<br>
<div class="text-center">
<%= link_to 'Back', news_histories_path, class: "btn btn-outline-danger" %>
</div>

app/views/news_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news_history.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @news_history.content %>
</p>



<%= link_to 'Edit', edit_news_history_path(@news_history) %> |
<%= link_to 'Back', news_histories_path %>